### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by radaniba** [py404/Django-OpenCV-Barcodes#1]
This is really cool @py404 
Wondering what are your thoughts on passing the information decoded from qr code into a form (populate fields), that is a relevant use case that I am wondering if can be extended on what you did here, what would be your approach

**Comment by py404** [comment]
Hello @radaniba, glad you liked this tiny project. My approach to handle that information is using Django forms. In the backend, after capturing the barcode data, you could pass this data to a Django form that can populate the fields. I am going to start with an example and push my code soon for your reference. I could also think of handling this in JavaScript.

**Comment by py404** [comment]
Hi @radaniba good day. Apologies for not getting back to you soon (been busy). I have added a feature example to save a valid QR code and fetch data using Ajax request to a form. Please find those changes in this commit 6b2cda1699ce1ac464b2c6a486ca025d2578e86b and in the latest commit I've updated the README with some GIF examples.

Please feel free to re-open the issue if that is not what you're after :-).
